ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/RR HH24:MI:SS';
SET PAGESIZE 3000;
SET LINESIZE 500;
SET TIME ON;
SET TRIMSPO ON;
SET TAB OFF;
SET TIMING ON;

COLUMN OWNER FORMAT A30
COLUMN DIRECTORY_NAME FORMAT A20
COLUMN DIRECTORY_PATH FORMAT A80
COLUMN DB_LINK FORMAT A30
COLUMN HOST FORMAT A30
COLUMN FILE_NAME FORMAT A80
COLUMN BYTES FORMAT 99999999999999
COLUMN MAXBYTES FORMAT 99999999999999
COLUMN VALUE FORMAT a50
COLUMN DISPLAY_VALUE FORMAT a50
COLUMN DEFAULT_VALUE FORMAT a30
COLUMN DESCRIPTION FORMAT a100
COLUMN UPDATE_COMMENT FORMAT a30
COLUMN WHAT FORMAT A80
COLUMN USERNAME FORMAT a30
COLUMN ACCOUNT_STATUS FORMAT a30
COLUMN USER_ID FORMAT a30
COLUMN CREATED FORMAT a50
COLUMN EXPIRY_DATE FORMAT a30
COLUMN LOCK_DATE FORMAT a30
COLUMN PASSWORD FORMAT a30

set sqlprompt "_user'@'_connect_identifier > "
host title &_user@&_connect_identifier